---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: "https://vault.zachary.day"
      path: "eks-demo-kv"
      version: "v2"
      auth:
        jwt:
          path: "eks-demo-jwt"
          role: external-secrets
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "vault-sa"
              namespace: external-secrets
            audiences:
            - vault
            expirationSeconds: 600