---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- ../default
patches:
- patch: |-
    - op: replace
      path: /spec/provider/vault/path
      value: eks-demo-kv
    - op: replace
      path: /spec/provider/vault/auth/jwt/path
      value: eks-demo-jwt
  target:
    group: external-secrets.io
    kind: ClusterSecretStore
    name: vault