apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- namespace.yaml
helmCharts:
- name: external-secrets
  includeCRDs: true
  namespace: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.18.2
  valuesFile: values.yaml
