---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- ../../base
- external-secrets.yaml
images:
- name: registry.k8s.io/external-dns/external-dns
  newTag: v0.18.0
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-token
            key: api-token
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - --source=service
        - --source=ingress
        - --source=gateway-httproute
        - --source=gateway-grpcroute
        - --registry=noop
        - --policy=upsert-only
        - --provider=cloudflare
        - --cloudflare-proxied
        - --cloudflare-record-comment="provisioned by external-dns"
  target:
    group: apps
    kind: Deployment
    name: external-dns