apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jupyterhub
    component: singleuser-server
    release: jupyterhub
  namespace: jupyter
  name: network-debugger
spec:
  containers:
  - name: debugger
    image: wbitt/network-multitool
    command: [ "/bin/bash" ]
    args:
    - "-c"
    - "sleep infinity"
  restartPolicy: OnFailure
  serviceAccountName: notebook2app
  tolerations:
  - effect: PreferNoSchedule
    key: spotInstance
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
