apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../default
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: notebook2app.zachary.day
    - op: replace
      path: /spec/tls/0/hosts/0
      value: notebook2app.zachary.day
  target:
    group: networking.k8s.io
    kind: Ingress
    name: argocd-server-ingress