apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
images:
- name: registry.k8s.io/external-dns/external-dns
  newTag: v0.18.0