apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyter
resources:
- ../../base
- external-secrets.yaml
- gateway.yaml
patches:
- patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: jupyterhub
- patch: |-
    - op: add
      path: /spec/storageClassName
      value: cephfs
  target:
    kind: PersistentVolumeClaim
    name: hub-db-dir
- patch: |-
    - op: add
      path: /spec/egress/-
      value:
        ports:
        - port: 6443
          protocol: TCP
        to:
        - ipBlock:
            cidr: 10.202.70.10/32
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: singleuser