---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- ingress.yaml

patches:
- patch: |-
    apiVersion: v1
    data:
      kustomize.buildOptions: --enable-helm
      resource.compareoptions: |
        ignoreAggregatedRoles: true
    kind: ConfigMap
    metadata:
      name: argocd-cm
      namespace: argocd