apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - ../../base
patches:
# KodeKloud AWS Playground does not allow external load balancers :(
# https://kodekloud.com/community/t/can-i-create-load-balancer-and-ingress-controller-in-eks-of-aws-cloud-playground/392441
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30080
    - op: add
      path: /spec/ports/1/nodePort
      value: 30443
  target:
    kind: Service
    name: ingress-nginx-controller